# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Code Build Check

on:
  push:
    branches:
      - 'develop'
      - 'main'
  pull_request:
    branches:
      - 'develop'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print
        run: env | sort
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: get caller identity
        id: get-aws-account-id
        run: |
          echo aai=$(aws sts get-caller-identity --query Account --output text)
          echo "bucket-name=${aai}-${GITHUB_REPOSITORY_OWNER}">> $GITHUB_OUTPUT
      - name: Print
        run: echo "${CONFIG_STATE_BUCKET_NAME}"
        env:
          CONFIG_STATE_BUCKET_NAME: "${{ steps.get-aws-account-id.outputs.bucket-name }}"

#      - uses: hashicorp/setup-terraform@v3
#      - run: terraform init -backend-config="region=${CONFIG_STATE_BUCKET_REGION}" -backend-config="bucket=${CONFIG_STATE_BUCKET_NAME}" -backend-config="key=${CONFIG_STATE_BUCKET_KEY}"
#        env:
#          CONFIG_STATE_BUCKET_REGION: ${{ secrets.CONFIG_STATE_BUCKET_REGION }}
#          CONFIG_STATE_BUCKET_NAME: "${{ steps.get-aws-account-id.outputs.aws-account-id }}${{env.GITHUB_REPOSITORY_OWNER}}"
#          CONFIG_STATE_BUCKET_KEY: ${{ secrets.CONFIG_STATE_BUCKET_KEY }}
#      - id: plan
#        run: terraform plan
#
