# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Code Build Check

on:
  push:
    branches:
      - 'develop'
      - 'main'
  pull_request:
    branches:
      - 'develop'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print
        run: env | sort
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: get caller identity
        id: get-aws-account-id
        run: |
          aai=$(aws sts get-caller-identity --query Account --output text)
          bucket=bucket-name=${aai}-${GITHUB_REPOSITORY_OWNER_ID}
          echo "${bucket}">> $GITHUB_OUTPUT
        env:
          CONFIG_STATE_BUCKET_REGION: ${{ secrets.CONFIG_STATE_BUCKET_REGION }}
          CONFIG_STATE_BUCKET_NAME: "${{ steps.get-aws-account-id.outputs.bucket-name }}"
      - name: create bucket
        id: create-bucket
        run: |
          aws s3api create-bucket --bucket 824591438121-184552102 --create-bucket-configuration LocationConstraint=eu-central-1 --region eu-central-1 > /dev/null 2> /dev/null
        env:
          CONFIG_STATE_BUCKET_REGION: ${{ secrets.CONFIG_STATE_BUCKET_REGION }}
          CONFIG_STATE_BUCKET_NAME: "${{ steps.get-aws-account-id.outputs.bucket-name }}"
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init -backend-config="region=${CONFIG_STATE_BUCKET_REGION}" -backend-config="bucket=${CONFIG_STATE_BUCKET_NAME}" -backend-config="key=${GITHUB_REPOSITORY_ID}"
        env:
          CONFIG_STATE_BUCKET_REGION: ${{ secrets.CONFIG_STATE_BUCKET_REGION }}
          CONFIG_STATE_BUCKET_NAME: "${{ steps.get-aws-account-id.outputs.bucket-name }}"
      - id: plan
        run: terraform plan


